export {default as Home} from './home/Home'
export {default as About} from './about/About'
export {default as Media} from './media/Media'
export {default as Events} from './events/Events'
export {default as Give} from './give/Give'
export {default as Contact} from './contact/Contact'
export {default as Subtext} from './subtext/Subtext'